// Liste de mots interdits par défaut, chargeable depuis /setup → 🤖 → 📥.
// Les mots sont comparés sans accents et en minuscules, par mot entier
// (les expressions avec espaces sont cherchées telles quelles).
// Adapte cette liste à ton serveur : certains termes (cheat, argent…) peuvent
// être légitimes selon ton activité — supprime-les via le bouton 📝.
module.exports = [
  // ── Insultes françaises ──
  'connard',
  'connasse',
  'encule',
  'enculee',
  'fils de pute',
  'fdp',
  'nique ta mere',
  'ntm',
  'salope',
  'petasse',
  'grognasse',
  'batard',
  'trou du cul',
  'sous merde',
  'grosse merde',
  'va crever',
  'suicide toi',

  // ── Propos haineux / discriminatoires FR ──
  'negre',
  'negro',
  'bougnoule',
  'bicot',
  'youpin',
  'chintok',
  'crouille',
  'pd',
  'tapette',
  'tarlouze',
  'tafiole',
  'fiotte',
  'mongol',
  'gogol',
  'triso',
  'attarde',

  // ── Insultes / slurs anglais ──
  'bitch',
  'whore',
  'slut',
  'cunt',
  'faggot',
  'fag',
  'nigger',
  'nigga',
  'retard',
  'retarded',
  'motherfucker',
  'asshole',
  'dickhead',
  'kys',
  'kill yourself',

  // ── Scam / arnaques ──
  'free nitro',
  'nitro gratuit',
  'nitro gratis',
  'discord gift gratuit',
  'argent facile',
  'double ton argent',
  'methode argent',
  'money method',
  'compte gratuit',
  'comptes gratuits',
  'generateur de compte',
  'account generator',
  'carding',
  'fullz',
  'methode refund',
  'refund method',
  'cashout',

  // ── Malware / vol de comptes Discord ──
  'token grabber',
  'grabber',
  'stealer',
  'ip logger',
  'ip grabber',
  'selfbot',
  'self bot',
  'token log',
  'vol de compte',
  'account stealer',

  // ── Cheats / attaques ──
  'aimbot',
  'wallhack',
  'esp hack',
  'mod menu',
  'hwid spoofer',
  'spoofer',
  'ddos',
  'booter',
  'stresser',
  'ip puller',
];
